name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/crecita-devops-key2.pem
          chmod 600 ~/.ssh/crecita-devops-key2.pem

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H 3.223.140.174 >> ~/.ssh/known_hosts

      - name: Run Ansible deployment
        run: |
          ansible-playbook \
            -i ansible/inventory.ini \
            ansible/deploy.yml
